export const translations = {
  en: {
    'title-business-ops': 'Business Operations | Ops Online Support',
    'hero-title': 'Business Operations Support',
    'hero-subtitle': 'Streamline your business operations and free up your time to focus on growth.',
    'cta-learn': 'Learn More',
    'modal-learn-more': 'Learn More',
    'modal-ask-chattia': 'Ask Chattia',
    'modal-join-us-title': 'Join Us',
    'modal-contact-us-title': 'Contact Us',
    'form-name': 'Name',
    'form-email': 'Email',
    'form-phone': 'Phone',
    'form-interest': 'What are you interested about?',
    'form-select-option': 'Select an option',
    'form-about': 'Tell us about yourself',
    'form-submit': 'Submit',
    'form-contact-number': 'Contact Number',
    'form-preferred-date': 'Preferred Date',
    'form-preferred-time': 'Preferred Time',
    'form-comments': 'Comments',
    'form-send': 'Send',
    'service-business-ops': 'Business Operations',
    'service-contact-center': 'Contact Center',
    'service-it-support': 'IT Support',
    'service-professionals': 'Professionals',
    'chatbot-title': 'OPS AI Chatbot',
    'chatbot-placeholder': 'Type your message...',
    'chatbot-human-check': 'I am human',
  },
  es: {
    'title-business-ops': 'Operaciones Comerciales | Soporte en línea',
    'hero-title': 'Soporte de Operaciones Comerciales',
    'hero-subtitle': 'Optimice sus operaciones y libere su tiempo para concentrarse en el crecimiento.',
    'cta-learn': 'Aprende Más',
    'modal-learn-more': 'Aprende Más',
    'modal-ask-chattia': 'Pregúntale a Chattia',
    'modal-join-us-title': 'Únete a Nosotros',
    'modal-contact-us-title': 'Contáctanos',
    'form-name': 'Nombre',
    'form-email': 'Correo Electrónico',
    'form-phone': 'Teléfono',
    'form-interest': '¿Qué te interesa?',
    'form-select-option': 'Seleccione una opción',
    'form-about': 'Háblanos de ti',
    'form-submit': 'Enviar',
    'form-contact-number': 'Número de Contacto',
    'form-preferred-date': 'Fecha Preferida',
    'form-preferred-time': 'Hora Preferida',
    'form-comments': 'Comentarios',
    'form-send': 'Enviar',
    'service-business-ops': 'Operaciones Comerciales',
    'service-contact-center': 'Centro de Contacto',
    'service-it-support': 'Soporte TI',
    'service-professionals': 'Profesionales',
    'chatbot-title': 'Chatbot OPS AI',
    'chatbot-placeholder': 'Escriba su mensaje...',
    'chatbot-human-check': 'Soy humano',
  },
};

export const services = {
  businessOps: {
    icon: '<i class="fa-solid fa-gears"></i>',
    img: 'https://placehold.co/600x400/00c4ff/fff?text=Operations',
    learn: 'business-ops.html',
    en: {
      title: 'Business Operations',
      desc: 'Optimize your workflows, manage staffing, and improve processes to scale efficiently.',
      modal: {
        imgAlt: 'A team collaborating on business operations',
        content: 'Our Business Operations service provides end-to-end solutions to help you manage your daily business activities.',
        features: ['Process automation', 'Supply chain management', 'Resource allocation', 'Performance monitoring'],
      },
    },
    es: {
      title: 'Operaciones Comerciales',
      desc: 'Optimice sus flujos de trabajo, gestione el personal y mejore los procesos para escalar de manera eficiente.',
      modal: {
        imgAlt: 'Un equipo colaborando en operaciones comerciales',
        content: 'Nuestro servicio de Operaciones Comerciales ofrece soluciones de principio a fin para ayudarle a gestionar sus actividades comerciales diarias.',
        features: ['Automatización de procesos', 'Gestión de la cadena de suministro', 'Asignación de recursos', 'Monitoreo del rendimiento'],
      },
    },
  },
  contactCenter: {
    icon: '<i class="fa-solid fa-headset"></i>',
    img: 'https://placehold.co/600x400/ff3bdb/fff?text=Contact%20Center',
    learn: 'contact-center.html',
    en: {
      title: 'Contact Center',
      desc: 'Provide exceptional customer service with our expert contact center solutions, available 24/7.',
      modal: {
        imgAlt: 'Contact center agents with headsets',
        content: 'Our Contact Center services are designed to improve customer satisfaction and streamline communication channels.',
        features: ['24/7 multilingual support', 'Technical support', 'Customer feedback analysis', 'Inbound and outbound calls'],
      },
    },
    es: {
      title: 'Centro de Contacto',
      desc: 'Ofrezca un servicio al cliente excepcional con nuestras soluciones expertas de centro de contacto, disponibles 24/7.',
      modal: {
        imgAlt: 'Agentes de centro de contacto con auriculares',
        content: 'Nuestros servicios de Centro de Contacto están diseñados para mejorar la satisfacción del cliente y optimizar los canales de comunicación.',
        features: ['Soporte multilingüe 24/7', 'Soporte técnico', 'Análisis de comentarios de clientes', 'Llamadas entrantes y salientes'],
      },
    },
  },
  itSupport: {
    icon: '<i class="fa-solid fa-computer"></i>',
    img: 'https://placehold.co/600x400/00c4ff/fff?text=IT%20Support',
    learn: 'it-support.html',
    en: {
      title: 'IT Support',
      desc: 'Resolve technical issues quickly and efficiently with our remote and on-site IT support services.',
      modal: {
        imgAlt: 'A person working on a computer',
        content: 'We provide comprehensive IT support to ensure your technology infrastructure runs smoothly and securely.',
        features: ['Remote troubleshooting', 'Network management', 'Software installation', 'Data security'],
      },
    },
    es: {
      title: 'Soporte TI',
      desc: 'Resuelva problemas técnicos de manera rápida y eficiente con nuestros servicios de soporte de TI.',
      modal: {
        imgAlt: 'Una persona trabajando en un ordenador',
        content: 'Ofrecemos soporte de TI integral para garantizar que su infraestructura tecnológica funcione sin problemas y de forma segura.',
        features: ['Solución de problemas remota', 'Gestión de red', 'Instalación de software', 'Seguridad de datos'],
      },
    },
  },
  professionalServices: {
    icon: '<i class="fa-solid fa-users"></i>',
    img: 'https://placehold.co/600x400/ff3bdb/fff?text=Professional%20Services',
    learn: 'professional-services.html',
    en: {
      title: 'Professional Services',
      desc: 'Leverage our expertise for strategic planning, project management, and business consulting to achieve your goals.',
      modal: {
        imgAlt: 'A group of professionals in a meeting',
        content: 'Our team of experts provides professional services to help your business grow and achieve its full potential.',
        features: ['Strategic planning', 'Project management', 'Business consulting', 'Financial analysis'],
      },
    },
    es: {
      title: 'Servicios Profesionales',
      desc: 'Aproveche nuestra experiencia para la planificación estratégica, la gestión de proyectos y la consultoría empresarial para lograr sus objetivos.',
      modal: {
        imgAlt: 'Un grupo de profesionales en una reunión',
        content: 'Nuestro equipo de expertos ofrece servicios profesionales para ayudar a su empresa a crecer y alcanzar su máximo potencial.',
        features: ['Planificación estratégica', 'Gestión de proyectos', 'Consultoría empresarial', 'Análisis financiero'],
      },
    },
  },
};
